services:
  - type: web
    name: nvaistat-laravel
    env: php
    plan: free
    branch: main
    repo: https://github.com/SadouMhamed/Aistats
    buildCommand: bash scripts/render-deploy.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      # Laravel Configuration
      - key: APP_NAME
        value: "Nvaistat"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:TRhxbxF89CizRUWfQiOsx0Rx8lq+jNiVTjLhcoCIJL8=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://nvaistat-laravel.onrender.com

      # Supabase Database Configuration
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-eu-west-3.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.hrjjjaxmdvhabzbkwbgg
      - key: DB_PASSWORD
        value: nvaistat2024prod!

      # Supabase API Configuration
      - key: SUPABASE_URL
        value: https://hrjjjaxmdvhabzbkwbgg.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyampqYXhtZHZoYWJ6Ymt3YmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjI4NjQsImV4cCI6MjA2NjYzODg2NH0.m_6Ruc9k0Js6Nu4PSjUG86BDnEm5YXOb81ldBDE5hb8
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyampqYXhtZHZoYWJ6Ymt3YmdnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTA2Mjg2NCwiZXhwIjoyMDY2NjM4ODY0fQ.m51UsEoq3eLOQLjQy06tDfEli9s7J87RGMYHtuqCMpM

      # Application Configuration
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

      # Mail Configuration (Optional)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"

      # Logging
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug
