services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    repo: https://github.com/SadouMhamed/Aistats
    buildCommand: "composer install && php artisan config:cache && php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: à_remplir
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: à_remplir
      - key: DB_USERNAME
        value: à_remplir
      - key: DB_PASSWORD
        value: à_remplir
