services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    repo: https://github.com/SadouMhamed/Aistats
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:x8EWUkuQQtgku9NEu+6d01ETJ4zYi0P3sQOzH2tEANA=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1fbq0je5dus73fqpo0g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: walidpostgres
      - key: DB_USERNAME
        value: walidpostgres_user
      - key: DB_PASSWORD
        value: 2d1OKOmNxHFlG8JQFp2ryH8tdXxbxHh8
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_DEBUG
        value: false
      - key: FILESYSTEM_DISK
        value: public
